### ISSUE TITLE
About FOSIL blurb

### ISSUE THREAD

**Issue by jvcasillas** [fosil-project/fosil-project.github.io#11]
Draft (leave comments/suggestions):

The purpose of this site is to help foster open science in linguistics (FOSIL).
The early 2010's saw the reproducibility crisis take hold of the psychological sciences. 
As a consequence, there's been a push for increased transparency and reproducible methodology to help mitigate the effects of questionable research practices. 
The resulting methodological framework and associated techniques, now referred to as open science, have reshaped research methods in psychology and have slowly but surely made their way into adjacent fields, such as linguistics.
Important considerations often overlooked in the wake of the open science movement deal with (1) how linguists actually learn open science practices and (2) how senior researchers can train the next generation of linguists.
Few, if any, researchers have had explicit instruction on the practices of open science as part of their professional training.
Nonetheless, today's speech researcher is expected to be up to date on the current protocols of open science in order incorporate the methodological practices aimed at improving reproducibility/replicability. 
The FOSIL project aims to make open science practices clear and accessible to people conducting research in the field of linguistics.

**Comment by kparrish92** [comment]
- I think we could add a sentence between the first and second sentence, just because the jump from linguistics to psychology feels a little abrupt.
- "Few, if any, researchers have had explicit instruction on the practices of open science as part of their professional training.
Nonetheless, today's speech researcher is expected to be up to date on the current protocols of open science in order incorporate the methodological practices aimed at improving reproducibility/replicability." - Since this is a living document , maybe we could add "As of 2023, few, if any...". Maybe this way the reader will wonder whether things have changed as we move forward in time. 
- Also, "if any" - I feel like I actually got training in this, because of Joseph.  Maybe "Few researchers..."

**Comment by nmrodriguez** [comment]
- I agree with @kparrish92 's first comment. Even adding something in the second sentence like ".., which can extend to other fields of study, like linguistics" could solve the abrupt jump. OR start with "The early 2010's...." and after "The resulting methodological framework..." add "The purpose of this site is to help foster open science in linguistics (FOSIL)." that way nothing is abrupt.
- Is adding "today's speech researcher" limiting the scope of the project to just people who study speech data? (this is a stupid question of me, I just really don't know if other linguists would call themselves speech researchers)

**Comment by jvcasillas** [comment]
Great suggestions. Thanks, @kparrish92 @nmrodriguez. I'll come back to this tomorrow. 

I was also thinking it would be good to weave into this paragraph something about linguistics being left behind... turning into a fossil (*fosil) if we don't adopt open science methods. Something silly like that to explain the wug. Still thinking about how to go about that.
